import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getFirestore,doc,onSnapshot,setDoc,collection,addDoc,updateDoc,deleteDoc} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
const config={apiKey:'AIzaSyCR8u4sW9C6r95EQs9STD44OmFVIgw7kVw',authDomain:'barrio-fiesta-bday--jex.firebaseapp.com',projectId:'barrio-fiesta-bday--jex',storageBucket:'barrio-fiesta-bday--jex.firebasestorage.app',messagingSenderId:'356981002942',appId:'1:356981002942:web:dfde56c2e337b6c57e84ef'};
const app=initializeApp(config),db=getFirestore(app);let editable=true,items={},details={},unsubs=[];
const sections=[{id:'food',title:'🍲 Food & Drinks',fields:[['name','Food / Drink'],['assigned','Assigned Person'],['supplier','Supplier'],['quantity','Quantity'],['price','Total Price (₱)'],['status','Status']]},{id:'suppliers',title:'🤝 Suppliers',fields:[['name','Supplier / Service'],['contact','Contact Details'],['assigned','Assigned Person'],['price','Quoted Price (₱)'],['status','Status']]},{id:'program',title:'🎤 Program Flow',fields:[['time','Time'],['name','Activity / Sequence'],['assigned','Person in Charge'],['notes','Notes']]},{id:'games',title:'🎯 Games & Prizes',fields:[['name','Game'],['assigned','Facilitator'],['prize','Prize'],['quantity','No. of Prizes'],['price','Total Cost (₱)'],['status','Status']]}];
const $=id=>document.getElementById(id),peso=n=>'₱'+Number(n||0).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2});
function notify(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),4500)}
function el(tag,text){const e=document.createElement(tag);e.textContent=text??'';return e}
function showDetails(){const v=$('detailView');v.replaceChildren();for(const [key,label] of [['celebrant','Celebrant'],['date','Date'],['time','Time'],['venue','Venue'],['notes','Notes']]){const p=el('p',label+': '+(details[key]||'To be announced'));v.append(p)}for(const input of $('detailForm').elements){if(input.name)input.value=details[input.name]??''}}
function showSection(s){const target=$('list-'+s.id);target.replaceChildren();const records=items[s.id]||[];if(!records.length){target.append(el('p','No entries yet.'));return}const wrap=el('div');wrap.className='tablewrap';const table=el('table'),thead=el('thead'),tr=el('tr');for(const [,label] of s.fields)tr.append(el('th',label));if(editable)tr.append(el('th','Actions'));thead.append(tr);table.append(thead);const body=el('tbody');for(const record of records){const row=el('tr');for(const [key] of s.fields){row.append(el('td',key==='price'?peso(record[key]):record[key]||'—'))}if(editable){const td=el('td'),edit=el('button','Edit'),del=el('button','Delete');edit.className='secondary';del.className='danger';edit.onclick=()=>editRecord(s,record);del.onclick=async()=>{if(confirm('Delete this entry?'))try{await deleteDoc(doc(db,s.id,record.id));notify('Deleted')}catch(e){notify(e.message)}};td.append(edit,' ',del);row.append(td)}body.append(row)}table.append(body);wrap.append(table);target.append(wrap)}
function editRecord(s,record){const form=$('form-'+s.id);form.dataset.editId=record.id;for(const [key] of s.fields)form.elements.namedItem(key).value=record[key]??'';form.scrollIntoView({behavior:'smooth',block:'center'})}
function render(){document.body.classList.toggle('can-edit',editable);$('costPanel').classList.toggle('hidden',!editable);$('costRestricted').classList.toggle('hidden',editable);showDetails();for(const s of sections)showSection(s);const total=sections.filter(s=>s.id!=='program').reduce((a,s)=>a+(items[s.id]||[]).reduce((b,r)=>b+Number(r.price||0),0),0),budget=Number(details.budget||0);$('budget').textContent=peso(budget);$('spent').textContent=peso(total);$('balance').textContent=peso(budget-total);$('count').textContent=sections.reduce((n,s)=>n+(items[s.id]||[]).length,0);$('costBudget').textContent=peso(budget);$('costSpent').textContent=peso(total);$('costRemaining').textContent=peso(budget-total);const tbody=$('costRows');tbody.replaceChildren();for(const s of sections.filter(s=>s.id!=='program')){const tr=el('tr');tr.append(el('td',s.title),el('td',peso((items[s.id]||[]).reduce((a,r)=>a+Number(r.price||0),0))));tbody.append(tr)}}
function buildSections(){for(const s of sections){const section=el('section');section.className='card';section.id=s.id;const title=el('h2',s.title);section.append(title);const list=el('div');list.id='list-'+s.id;section.append(list);const form=el('form');form.id='form-'+s.id;form.className='edit-only';const fields=el('div');fields.className='row-fields';for(const [key,label] of s.fields){const wrapper=el('div'),l=el('label',label),input=el('input');input.name=key;input.placeholder=label;input.type=key==='price'||key==='quantity'?'number':'text';if(input.type==='number'){input.min='0';input.step=key==='price'?'0.01':'1'}wrapper.append(l,input);fields.append(wrapper)}form.append(fields);const actions=el('div');actions.className='actions';const save=el('button','Save Entry');save.type='submit';const cancel=el('button','Clear / Cancel Edit');cancel.type='button';cancel.className='secondary';cancel.onclick=()=>{form.reset();delete form.dataset.editId};actions.append(save,cancel);form.append(actions);form.onsubmit=async e=>{e.preventDefault();if(!editable)return;const obj={};for(const [key] of s.fields)obj[key]=form.elements.namedItem(key).value.trim();try{if(form.dataset.editId)await updateDoc(doc(db,s.id,form.dataset.editId),obj);else await addDoc(collection(db,s.id),obj);form.reset();delete form.dataset.editId;notify('Saved successfully')}catch(err){notify('Save failed: '+err.message)}};section.append(form);$('dynamicSections').append(section)}}
buildSections();$('detailForm').onsubmit=async e=>{e.preventDefault();if(!editable)return;const values=Object.fromEntries(new FormData(e.currentTarget));try{await setDoc(doc(db,'event','details'),values);notify('Event details saved')}catch(err){notify(err.message)}};
$('exportBtn').onclick=()=>{if(!editable)return;const rows=[['Category','Item','Assigned','Price']];for(const s of sections.filter(s=>s.id!=='program'))for(const r of items[s.id]||[])rows.push([s.id,r.name||'',r.assigned||'',r.price||'']);const csv=rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\r\n');const a=document.createElement('a'),url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.href=url;a.download='barrio-fiesta-costing.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
function clearListeners(){unsubs.forEach(u=>u());unsubs=[]}
function subscribe(){clearListeners();const publicErr=e=>{$('connection').textContent='Connection issue';notify(e.message)};unsubs.push(onSnapshot(doc(db,'event','details'),snap=>{details=snap.exists()?snap.data():{};render();$('connection').textContent='Live updates active'},publicErr));for(const s of sections){unsubs.push(onSnapshot(collection(db,s.id),snap=>{items[s.id]=snap.docs.map(d=>({id:d.id,...d.data()}));render()},publicErr))}}
render();
subscribe();
